### ISSUE TITLE
Trainig code & evaluation accurcay

### ISSUE THREAD

**Issue by Ivamcoder** [DhruvJawalkar/PyTorch-OpenPose-Realtime-Multi-Person-2D-Pose-Estimation-using-Part-Affinity-Fields#1]
Hi @DhruvJawalkar ,

Thanks for sharing the results,I really appreciate if you share your complete codes.

Thanks,

**Comment by DhruvJawalkar** [comment]
Hi @Ivamcoder, 
You could go through the estimate-pose.ipynb
I have now updated the [notebook](https://github.com/DhruvJawalkar/PyTorch-OpenPose-Realtime-Multi-Person-2D-Pose-Estimation-using-Part-Affinity-Fields/blob/master/estimate-pose.ipynb) with functions to evaluate on sample image, video. 

<img width="1045" alt="Screenshot 2019-05-20 at 12 45 24 PM" src="https://user-images.githubusercontent.com/5371976/58047591-59000980-7afd-11e9-8e25-396727cf620a.png">

**Comment by DhruvJawalkar** [comment]
<img width="767" alt="Screenshot 2019-05-20 at 12 46 18 PM" src="https://user-images.githubusercontent.com/5371976/58047750-b98f4680-7afd-11e9-87ac-5e20883e1c3a.png">

just skip the cell with dataset, dataloader, load the model and you should be able to evaluate.
